env:
  CIRRUS_CLONE_DEPTH: 1

freebsd_12_task:
  freebsd_instance:
    image: freebsd-12-1-release-amd64
  install_script:
    - pkg install -y autoconf automake fusefs-libs libtool pkgconf
  build_script:
    - sh autogen.sh
    - ./configure
    - make
